# Generated by Django 2.2.14 on 2020-11-20 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='created',
            field=models.DateTimeField(auto_created=True, null=True),
        ),
        migrations.AddField(
            model_name='manager',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
