# Generated by Django 2.2.14 on 2020-11-20 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='created',
            field=models.DateTimeField(auto_created=True, null=True),
        ),
        migrations.AddField(
            model_name='area',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
