# Generated by Django 2.2.14 on 2020-11-19 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0001_initial'),
        ('managers', '0001_initial'),
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='area',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='areas.Area'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='managers',
            field=models.ManyToManyField(related_name='empleados', to='managers.Manager'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='telefono',
            field=models.CharField(default='', max_length=20),
        ),
    ]
