# Generated by Django 2.2.14 on 2020-11-20 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0002_auto_20201119_0529'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='created',
            field=models.DateTimeField(auto_created=True, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
